eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/arpitbhatt027/microservice-config-server